### ISSUE TITLE
Update script broke my hat?

### ISSUE THREAD

**Issue by Testing1User** [sixfab/sixfab-power-python-api#13]
Hi,

I updated to version 0.3.3 due to having the int/none type errors.
however, after the update finished my L1, L2 LED and S1, S2 buttons have stopped working?? 
Can't send any command at all to the hat. 
Any inputs would be great.
pic for referenec

[https://imgur.com/a/ofH93gc](url)

**Comment by Testing1User** [comment]
@selengalp

**Comment by ensarkarabudak** [comment]
Could you help to provide more information about your issue? What was the behavior of the LEDs when running the update script?
Is there any log file?
