### ISSUE TITLE
vcgencmd not available on RPI4-64 bit builds

### ISSUE THREAD

**Issue by rcalderon04** [sixfab/sixfab-power-python-api#14]
get_system_temp() uses vcgencmd to read RPI temperature which is not available on some RPI4-64 bit builds. Is it possible to put a check flag for vcgencmd and find another command to read temperature command?

**Comment by selengalp** [comment]
Hello,
You can simply install vcgencmd by using `sudo pip3 install vcgencmd`. We will add it to the next version of the API as a requirement. Thanks for the feedback.
