### ISSUE TITLE
No module named 'power_api'

### ISSUE THREAD

**Issue by micpie1** [sixfab/sixfab-power-python-api#6]
api successfully install and try to run example read_sensors.py but got following error :

root@POWER-MONITOR:/home/pi/MONITOR# python3 ./read_sensors.py 
Traceback (most recent call last):
  File "./read_sensors.py", line 1, in <module>
    from power_api import SixfabPower, Definition
ModuleNotFoundError: No module named 'power_api'
root@POWER-MONITOR:/home/pi/MONITOR#

**Comment by dcarpy** [comment]
What happens when you type:
pip3 show sixfab-power-python-api

**Comment by micpie1** [comment]
Hi ,

 

Here the result :

 

root@POWER-MONITOR:~# pip3 show sixfab-power-python-api

Name: sixfab-power-python-api

Version: 0.0.1

Summary: Sixfab power management service python api

Home-page: https://github.com/sixfab/sixfab-power-python-api

Author: Yasin Kaya

Author-email: yasinkaya.121@gmail.com

License: MIT

Location: /usr/local/lib/python3.7/dist-packages

Requires: crc16, smbus2

Required-by: 

root@POWER-MONITOR:~# 

 

but I found a workaround with using “import pms_api” and using the other names  for all the functions …

 

root@POWER-MONITOR:/home/pi/MONITOR# cat read_sensors.py 

#from power_api import SixfabPower, Definition

from pms_api import *

import time

 

#api = SixfabPower()

api = SixfabPMS()

 

 

print("************* Input Sensors **************")

print("Input Temp: " + str(api.getInputTemp()))

print("Input Voltage: " + str(api.getInputVoltage()))

print("Input Current: " + str(api.getInputCurrent()))

print("Input Power: " + str(api.getInputPower()))               #Required delay #default 50

 

print("************* System Sensors **************")

print("System Temp: " + str(api.getSystemTemp()))

 

Regards,

Michel

**Comment by dcarpy** [comment]
Interesting.  It works fine for me. I''l try to dig a little more.
Maybe upgrading would help, but I'm not sure:
pip3 install sixfab-power-python-api -U

**Comment by dcarpy** [comment]
Actually, looking at it further, upgrading should fix your problem.

**Comment by micpie1** [comment]
Hi,

 

Upgrading helps !! It work fine now !

 

Thanks,

Michel
