### ISSUE TITLE
'int' object is not subscriptable

### ISSUE THREAD

**Issue by ryancalderon04** [sixfab/sixfab-power-python-api#7]
error when trying to read any sensor (this is just an example of temperature)

running on rpi4, python 3.7.3, sixfab version: 0.0.2

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/power_api/power_api.py", line 102, in get_input_temp
    raw[PROTOCOL_HEADER_SIZE : COMMAND_SIZE_FOR_INT32 - 2], "big"
TypeError: 'int' object is not subscriptable

**Comment by ensarkarabudak** [comment]
try calling the function a few times

**Comment by ryancalderon04** [comment]
called over 10 times consecutively, all returned the same error. Are you thinking the i2c line is slave locked?

**Comment by ryancalderon04** [comment]
also, I've used 
$ i2cdetect -y 1
this returns a device with address 41, which looks to be the chip address Sixfab has hardcoded (command.py line 36)

**Comment by ryancalderon04** [comment]
debugging a bit: 
command.create_command(command.PROTOCOL_COMMAND_GET_INPUT_TEMP)
command.send_command() 
returns -4 --> (self.BYTE_SEND_FAILED)

I thought this was a library failure, but it looks like power_api.py does not include error handling. I'm not sure why the send_command() is failing

**Comment by ryancalderon04** [comment]
Also, I'm running inside a docker container

**Comment by Testing1User** [comment]
Hi,

Any update on this? Would appreciate a bit of help from the devs.
I also am having the same issue.

Running on RPI 3. Sixfab V 0.0.6

**Comment by ryancalderon04** [comment]
I could not get it working on RPI4. 

I switched to RPI3 and got it working, for the most part. I wrapped the library calls with my own functions using _retrying_
https://pypi.org/project/retrying/

The error still happens but at least now I have error handling for it. I'm not sure why RPI4 was totally unable successfully communicate.

**Comment by dcarpy** [comment]
Did you guys try stopping the PMS agent first?
sudo systemctl stop pms_agent.service

**Comment by Testing1User** [comment]
Hi,

Yes, I tried to stop it.
I get - Failed to stop pms_agent.service: Unit pms_agent.service not loaded.

I was getting the same results initially TypeError: 'int' object is not subscriptable. After a few tries the script just started working like normal and gave me the temp / all the sensor readings without any error handling or loops.

A bit confused as to why this could happen? Does the UPS Hat require some time to fully boot up ?
I have not changed any settings from friday.

**Comment by snrkl** [comment]
Having the same issue, without the power_agent service running:

`0 ~/bin $ python3
Python 3.7.3 (default, Dec 20 2019, 18:57:59)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from power_api import SixfabPower, Definition
>>> power = SixfabPower()
>>> power.get_fan_speed()
0
>>> power.get_fan_mode()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/power_api/power_api.py", line 1736, in get_fan_mode
    status = raw[PROTOCOL_HEADER_SIZE]
TypeError: 'NoneType' object is not subscriptable`

**Comment by dcarpy** [comment]
I get the same error.
I feel the firmware doesn't support the new commands yet? @ensarkarabudak ?

**Comment by snrkl** [comment]
Additionally to this, as soon as you hit a function that returns the 

> TypeError: 'NoneType' object is not subscriptable

error, it will kill all calls to previously working functions:

`snrkl@nitrogen`
`0 ~ $ python3`
`Python 3.7.3 (default, Dec 20 2019, 18:57:59)`
`[GCC 8.3.0] on linux`
`Type "help", "copyright", "credits" or "license" for more information.`
`>>>`
`>>> from power_api import SixfabPower, Definition`
`>>> import time`
`>>> power = SixfabPower()`
`>>>`
`>>>`
`>>> power.get_input_temp()`
`28.5`
`>>> power.get_input_voltage()`
`4.992`
`>>> power.get_battery_voltage()`
`4.202`
`>>> power.get_system_power()`
`0.648`
`>>> power.get_system_power()`
`0.432`
`>>> power.get_fan_speed()`
`0`
`>>> power.get_fan_health()`
`1`
`>>> power.get_fan_mode()`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/home/snrkl/.local/lib/python3.7/site-packages/power_api/power_api.py", line 1736, in get_fan_mode`
`    status = raw[PROTOCOL_HEADER_SIZE]`
`TypeError: 'NoneType' object is not subscriptable`
`>>>`
`>>> power.get_fan_health()`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/home/snrkl/.local/lib/python3.7/site-packages/power_api/power_api.py", line 442, in get_fan_health`
`    raw[PROTOCOL_HEADER_SIZE : COMMAND_SIZE_FOR_INT32 - 2], "big"`
`TypeError: 'NoneType' object is not subscriptable`
`>>>`
`>>> power.get_fan_speed()`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/home/snrkl/.local/lib/python3.7/site-packages/power_api/power_api.py", line 491, in get_fan_speed`
`    raw[PROTOCOL_HEADER_SIZE : COMMAND_SIZE_FOR_INT32 - 2], "big"`
`TypeError: 'NoneType' object is not subscriptable`
`>>>`

**Comment by selengalp** [comment]
> 
> 
> Having the same issue, without the power_agent service running:
> 
> `0 ~/bin $ python3
> Python 3.7.3 (default, Dec 20 2019, 18:57:59)
> [GCC 8.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > from power_api import SixfabPower, Definition
> > > > power = SixfabPower()
> > > > power.get_fan_speed()
> > > > 0
> > > > power.get_fan_mode()
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/usr/local/lib/python3.7/dist-packages/power_api/power_api.py", line 1736, in get_fan_mode
> > > > status = raw[PROTOCOL_HEADER_SIZE]
> > > > TypeError: 'NoneType' object is not subscriptable`

Hello snrkl, 
We released [a new firmware file](https://git.sixfab.com/sixfab-power/firmwares/src/branch/master/sixfab_pms_firmware_v0.3.3.bin) to solve your issue. You can update firmware by using [Sixfab Power Platform](https://power.sixfab.com) automatically. Or you can do it by using sixfab-power-python-api manually. Thank you for your feedback.

**Comment by snrkl** [comment]
> Hello snrkl,
> We released [a new firmware file](https://git.sixfab.com/sixfab-power/firmwares/src/branch/master/sixfab_pms_firmware_v0.3.3.bin) to solve your issue. You can update firmware by using [Sixfab Power Platform](https://power.sixfab.com) automatically. Or you can do it by using sixfab-power-python-api manually. Thank you for your feedback.

I can confirm that the 0.3.3 update seems to have solved this issue.. Thank you! 👍
